## 二、TenserFlow的核心概念

### 2-1 张量数据结构

一、常量张量

In [1]:
import numpy as np
import tensorflow as tf

i = tf.constant(1)
l = tf.constant(1, dtype=tf.int64)
f = tf.constant(1.23)
d = tf.constant(3.14, dtype=tf.double)
s = tf.constant("hello world")
b = tf.constant(True)

print(tf.int64 == np.int64)
print(tf.bool == np.bool)
print(tf.double == np.float64)
print(tf.string == np.unicode)

True
True
True
False


In [2]:
# 标量为0维（rank）张量，向量为1维张量，矩阵为2维张量
scalar = tf.constant(True)

print(tf.rank(scalar))
print(scalar.numpy().ndim)

tf.Tensor(0, shape=(), dtype=int32)
0


In [3]:
vector = tf.constant([1.0, 2.0, 3.0, 4.0])

print(tf.rank(vector))
print(np.ndim(vector.numpy()))

tf.Tensor(1, shape=(), dtype=int32)
1


In [4]:
matrix = tf.constant([[1.0, 2.0], [3.0, 4.0]])

print(tf.rank(matrix).numpy())
print(np.ndim(matrix))

2
2


In [6]:
tensor3 = tf.constant([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])
print(tensor3)
print(tf.rank(tensor3))

tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(3, shape=(), dtype=int32)


In [8]:
tensor4 = tf.constant([[[[1.0, 1.0], [2.0, 2.0]], [[3.0, 3.0], [4.0, 4.0]]],
    [[[5.0, 5.0], [6.0, 6.0]], [[7.0, 7.0], [8.0, 8.0]]]])
print(tensor4)
print(tf.rank(tensor4))

tf.Tensor(
[[[[1. 1.]
   [2. 2.]]

  [[3. 3.]
   [4. 4.]]]


 [[[5. 5.]
   [6. 6.]]

  [[7. 7.]
   [8. 8.]]]], shape=(2, 2, 2, 2), dtype=float32)
tf.Tensor(4, shape=(), dtype=int32)


In [9]:
# tf.cast改变张量的数据类型
# numpy方法将TensorFlow张量转化成numpy张量
# shape查看尺寸
h = tf.constant([123, 456], dtype=tf.int32)
f = tf.cast(h, tf.float32)
print(h.dtype, f.dtype)

<dtype: 'int32'> <dtype: 'float32'>


In [10]:
y = tf.constant([[1.0, 2.0], [3.0, 4.0]])
print(y.numpy())
print(y.shape)

[[1. 2.]
 [3. 4.]]
(2, 2)


In [11]:
u = tf.constant(u"你好 世界")
print(u.numpy())
print(u.numpy().decode("utf-8"))

b'\xe4\xbd\xa0\xe5\xa5\xbd \xe4\xb8\x96\xe7\x95\x8c'
你好 世界


二、变量张量

In [12]:
# 常量值不可以改变，常量的重新赋值相当于创造新的内存空间
c = tf.constant([1.0, 2.0])
print(c)
print(id(c))
c = c + tf.constant([1.0, 1.0])
print(c)
print(id(c))

tf.Tensor([1. 2.], shape=(2,), dtype=float32)
139911587568112
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
139911587566176


In [13]:
v = tf.Variable([1.0, 2.0], name="v")
print(v)
print(id(v))
v.assign_add([1.0, 1.0])
print(v)
print(id(v))

<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
139914534360784
<tf.Variable 'v:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>
139914534360784
